/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountingBalanceSheetRouteImport } from './routes/accounting.balance-sheet'
import { Route as AccountingCoaRouteImport } from './routes/accounting.coa'
import { Route as AccountingGstRouteImport } from './routes/accounting.gst'
import { Route as AccountingJournalRouteImport } from './routes/accounting.journal'
import { Route as AccountingPnlRouteImport } from './routes/accounting.pnl'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as AutomationIndexRouteImport } from './routes/automation.index'
import { Route as BankingIndexRouteImport } from './routes/banking.index'
import { Route as BankingConnectRouteImport } from './routes/banking.connect'
import { Route as BankingReconcileRouteImport } from './routes/banking.reconcile'
import { Route as BankingReviewRouteImport } from './routes/banking.review'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as InventoryWarehousesRouteImport } from './routes/inventory.warehouses'
import { Route as PosIndexRouteImport } from './routes/pos.index'
import { Route as PurchasesBillsRouteImport } from './routes/purchases.bills'
import { Route as PurchasesVendorsRouteImport } from './routes/purchases.vendors'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as SalesCustomersRouteImport } from './routes/sales.customers'
import { Route as SalesInvoicesRouteImport } from './routes/sales.invoices'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SalesInvoicesIdRouteImport } from './routes/sales.invoices.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingBalanceSheetRoute = AccountingBalanceSheetRouteImport.update({
  id: '/accounting/balance-sheet',
  path: '/accounting/balance-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingCoaRoute = AccountingCoaRouteImport.update({
  id: '/accounting/coa',
  path: '/accounting/coa',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingGstRoute = AccountingGstRouteImport.update({
  id: '/accounting/gst',
  path: '/accounting/gst',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingJournalRoute = AccountingJournalRouteImport.update({
  id: '/accounting/journal',
  path: '/accounting/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingPnlRoute = AccountingPnlRouteImport.update({
  id: '/accounting/pnl',
  path: '/accounting/pnl',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationIndexRoute = AutomationIndexRouteImport.update({
  id: '/automation/',
  path: '/automation/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingIndexRoute = BankingIndexRouteImport.update({
  id: '/banking/',
  path: '/banking/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingConnectRoute = BankingConnectRouteImport.update({
  id: '/banking/connect',
  path: '/banking/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingReconcileRoute = BankingReconcileRouteImport.update({
  id: '/banking/reconcile',
  path: '/banking/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingReviewRoute = BankingReviewRouteImport.update({
  id: '/banking/review',
  path: '/banking/review',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryWarehousesRoute = InventoryWarehousesRouteImport.update({
  id: '/inventory/warehouses',
  path: '/inventory/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesBillsRoute = PurchasesBillsRouteImport.update({
  id: '/purchases/bills',
  path: '/purchases/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesVendorsRoute = PurchasesVendorsRouteImport.update({
  id: '/purchases/vendors',
  path: '/purchases/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCustomersRoute = SalesCustomersRouteImport.update({
  id: '/sales/customers',
  path: '/sales/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesInvoicesRoute = SalesInvoicesRouteImport.update({
  id: '/sales/invoices',
  path: '/sales/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesInvoicesIdRoute = SalesInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesInvoicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting/balance-sheet': typeof AccountingBalanceSheetRoute
  '/accounting/coa': typeof AccountingCoaRoute
  '/accounting/gst': typeof AccountingGstRoute
  '/accounting/journal': typeof AccountingJournalRoute
  '/accounting/pnl': typeof AccountingPnlRoute
  '/banking/connect': typeof BankingConnectRoute
  '/banking/reconcile': typeof BankingReconcileRoute
  '/banking/review': typeof BankingReviewRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/purchases/bills': typeof PurchasesBillsRoute
  '/purchases/vendors': typeof PurchasesVendorsRoute
  '/sales/customers': typeof SalesCustomersRoute
  '/sales/invoices': typeof SalesInvoicesRouteWithChildren
  '/ai/': typeof AiIndexRoute
  '/automation/': typeof AutomationIndexRoute
  '/banking/': typeof BankingIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/pos/': typeof PosIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sales/invoices/$id': typeof SalesInvoicesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting/balance-sheet': typeof AccountingBalanceSheetRoute
  '/accounting/coa': typeof AccountingCoaRoute
  '/accounting/gst': typeof AccountingGstRoute
  '/accounting/journal': typeof AccountingJournalRoute
  '/accounting/pnl': typeof AccountingPnlRoute
  '/banking/connect': typeof BankingConnectRoute
  '/banking/reconcile': typeof BankingReconcileRoute
  '/banking/review': typeof BankingReviewRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/purchases/bills': typeof PurchasesBillsRoute
  '/purchases/vendors': typeof PurchasesVendorsRoute
  '/sales/customers': typeof SalesCustomersRoute
  '/sales/invoices': typeof SalesInvoicesRouteWithChildren
  '/ai': typeof AiIndexRoute
  '/automation': typeof AutomationIndexRoute
  '/banking': typeof BankingIndexRoute
  '/crm': typeof CrmIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/pos': typeof PosIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/sales': typeof SalesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sales/invoices/$id': typeof SalesInvoicesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting/balance-sheet': typeof AccountingBalanceSheetRoute
  '/accounting/coa': typeof AccountingCoaRoute
  '/accounting/gst': typeof AccountingGstRoute
  '/accounting/journal': typeof AccountingJournalRoute
  '/accounting/pnl': typeof AccountingPnlRoute
  '/banking/connect': typeof BankingConnectRoute
  '/banking/reconcile': typeof BankingReconcileRoute
  '/banking/review': typeof BankingReviewRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/purchases/bills': typeof PurchasesBillsRoute
  '/purchases/vendors': typeof PurchasesVendorsRoute
  '/sales/customers': typeof SalesCustomersRoute
  '/sales/invoices': typeof SalesInvoicesRouteWithChildren
  '/ai/': typeof AiIndexRoute
  '/automation/': typeof AutomationIndexRoute
  '/banking/': typeof BankingIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/pos/': typeof PosIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sales/invoices/$id': typeof SalesInvoicesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting/balance-sheet'
    | '/accounting/coa'
    | '/accounting/gst'
    | '/accounting/journal'
    | '/accounting/pnl'
    | '/banking/connect'
    | '/banking/reconcile'
    | '/banking/review'
    | '/inventory/warehouses'
    | '/purchases/bills'
    | '/purchases/vendors'
    | '/sales/customers'
    | '/sales/invoices'
    | '/ai/'
    | '/automation/'
    | '/banking/'
    | '/crm/'
    | '/inventory/'
    | '/pos/'
    | '/reports/'
    | '/sales/'
    | '/settings/'
    | '/sales/invoices/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting/balance-sheet'
    | '/accounting/coa'
    | '/accounting/gst'
    | '/accounting/journal'
    | '/accounting/pnl'
    | '/banking/connect'
    | '/banking/reconcile'
    | '/banking/review'
    | '/inventory/warehouses'
    | '/purchases/bills'
    | '/purchases/vendors'
    | '/sales/customers'
    | '/sales/invoices'
    | '/ai'
    | '/automation'
    | '/banking'
    | '/crm'
    | '/inventory'
    | '/pos'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/sales/invoices/$id'
  id:
    | '__root__'
    | '/'
    | '/accounting/balance-sheet'
    | '/accounting/coa'
    | '/accounting/gst'
    | '/accounting/journal'
    | '/accounting/pnl'
    | '/banking/connect'
    | '/banking/reconcile'
    | '/banking/review'
    | '/inventory/warehouses'
    | '/purchases/bills'
    | '/purchases/vendors'
    | '/sales/customers'
    | '/sales/invoices'
    | '/ai/'
    | '/automation/'
    | '/banking/'
    | '/crm/'
    | '/inventory/'
    | '/pos/'
    | '/reports/'
    | '/sales/'
    | '/settings/'
    | '/sales/invoices/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingBalanceSheetRoute: typeof AccountingBalanceSheetRoute
  AccountingCoaRoute: typeof AccountingCoaRoute
  AccountingGstRoute: typeof AccountingGstRoute
  AccountingJournalRoute: typeof AccountingJournalRoute
  AccountingPnlRoute: typeof AccountingPnlRoute
  BankingConnectRoute: typeof BankingConnectRoute
  BankingReconcileRoute: typeof BankingReconcileRoute
  BankingReviewRoute: typeof BankingReviewRoute
  InventoryWarehousesRoute: typeof InventoryWarehousesRoute
  PurchasesBillsRoute: typeof PurchasesBillsRoute
  PurchasesVendorsRoute: typeof PurchasesVendorsRoute
  SalesCustomersRoute: typeof SalesCustomersRoute
  SalesInvoicesRoute: typeof SalesInvoicesRouteWithChildren
  AiIndexRoute: typeof AiIndexRoute
  AutomationIndexRoute: typeof AutomationIndexRoute
  BankingIndexRoute: typeof BankingIndexRoute
  CrmIndexRoute: typeof CrmIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  PosIndexRoute: typeof PosIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/balance-sheet': {
      id: '/accounting/balance-sheet'
      path: '/accounting/balance-sheet'
      fullPath: '/accounting/balance-sheet'
      preLoaderRoute: typeof AccountingBalanceSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/coa': {
      id: '/accounting/coa'
      path: '/accounting/coa'
      fullPath: '/accounting/coa'
      preLoaderRoute: typeof AccountingCoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/gst': {
      id: '/accounting/gst'
      path: '/accounting/gst'
      fullPath: '/accounting/gst'
      preLoaderRoute: typeof AccountingGstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/journal': {
      id: '/accounting/journal'
      path: '/accounting/journal'
      fullPath: '/accounting/journal'
      preLoaderRoute: typeof AccountingJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/pnl': {
      id: '/accounting/pnl'
      path: '/accounting/pnl'
      fullPath: '/accounting/pnl'
      preLoaderRoute: typeof AccountingPnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/': {
      id: '/ai/'
      path: '/ai'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/': {
      id: '/automation/'
      path: '/automation'
      fullPath: '/automation/'
      preLoaderRoute: typeof AutomationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking/': {
      id: '/banking/'
      path: '/banking'
      fullPath: '/banking/'
      preLoaderRoute: typeof BankingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking/connect': {
      id: '/banking/connect'
      path: '/banking/connect'
      fullPath: '/banking/connect'
      preLoaderRoute: typeof BankingConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking/reconcile': {
      id: '/banking/reconcile'
      path: '/banking/reconcile'
      fullPath: '/banking/reconcile'
      preLoaderRoute: typeof BankingReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking/review': {
      id: '/banking/review'
      path: '/banking/review'
      fullPath: '/banking/review'
      preLoaderRoute: typeof BankingReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/warehouses': {
      id: '/inventory/warehouses'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses'
      preLoaderRoute: typeof InventoryWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/bills': {
      id: '/purchases/bills'
      path: '/purchases/bills'
      fullPath: '/purchases/bills'
      preLoaderRoute: typeof PurchasesBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/vendors': {
      id: '/purchases/vendors'
      path: '/purchases/vendors'
      fullPath: '/purchases/vendors'
      preLoaderRoute: typeof PurchasesVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/customers': {
      id: '/sales/customers'
      path: '/sales/customers'
      fullPath: '/sales/customers'
      preLoaderRoute: typeof SalesCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/invoices': {
      id: '/sales/invoices'
      path: '/sales/invoices'
      fullPath: '/sales/invoices'
      preLoaderRoute: typeof SalesInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/invoices/$id': {
      id: '/sales/invoices/$id'
      path: '/$id'
      fullPath: '/sales/invoices/$id'
      preLoaderRoute: typeof SalesInvoicesIdRouteImport
      parentRoute: typeof SalesInvoicesRoute
    }
  }
}

interface SalesInvoicesRouteChildren {
  SalesInvoicesIdRoute: typeof SalesInvoicesIdRoute
}

const SalesInvoicesRouteChildren: SalesInvoicesRouteChildren = {
  SalesInvoicesIdRoute: SalesInvoicesIdRoute,
}

const SalesInvoicesRouteWithChildren = SalesInvoicesRoute._addFileChildren(
  SalesInvoicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingBalanceSheetRoute: AccountingBalanceSheetRoute,
  AccountingCoaRoute: AccountingCoaRoute,
  AccountingGstRoute: AccountingGstRoute,
  AccountingJournalRoute: AccountingJournalRoute,
  AccountingPnlRoute: AccountingPnlRoute,
  BankingConnectRoute: BankingConnectRoute,
  BankingReconcileRoute: BankingReconcileRoute,
  BankingReviewRoute: BankingReviewRoute,
  InventoryWarehousesRoute: InventoryWarehousesRoute,
  PurchasesBillsRoute: PurchasesBillsRoute,
  PurchasesVendorsRoute: PurchasesVendorsRoute,
  SalesCustomersRoute: SalesCustomersRoute,
  SalesInvoicesRoute: SalesInvoicesRouteWithChildren,
  AiIndexRoute: AiIndexRoute,
  AutomationIndexRoute: AutomationIndexRoute,
  BankingIndexRoute: BankingIndexRoute,
  CrmIndexRoute: CrmIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  PosIndexRoute: PosIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
